os: linux
dist: bionic
language: python
cache:
  pip: true
  directories:
    - data/

jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9-dev
  allow_failures:
    - python: 3.9-dev

env:
  - TEST=unit
  - TEST=issue
  - TEST=console
  - TEST=examples
  - TEST=lint
  - TEST=typing

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

install:
  - check-manifest
  - python setup.py sdist bdist_wheel
  - twine check dist/*
  - pip install -e .[notebook,app,html]

script:
  - if [ $TEST == 'unit' ]; then pytest --cov=. tests/unit/; fi
  - if [ $TEST == 'issue' ]; then pytest --cov=. tests/issues/; fi
  - if [ $TEST == 'examples' ]; then pytest --cov=. --nbval tests/notebooks/; fi
  - if [ $TEST == 'console' ]; then pandas_profiling -h; fi
  - if [ $TEST == 'typing' ]; then pytest --mypy -m mypy .; fi
  - if [ $TEST == 'lint' ]; then pytest --black -m black src/; flake8 . --select=E9,F63,F7,F82 --show-source --statistics; fi

after_success:
  - codecov -F $TEST
