sudo: required
dist: xenial
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # TODO add 3.8-dev
install:
  - pip install -e .
script:
  - python -m unittest -v pandas_profiling.tests
