sudo: required
dist: xenial
language: python
cache: pip
python:
#  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

jobs:
  include:
    - stage: "Tests"
      name: "Unit tests"
      script: pytest --nbval --cov=./ --sanitize-with tests/sanitize-notebook.cfg
    - stage: "Tests"
      name: "Console tests"
      script: pandas_profiling -h

after_success:
  - codecov
