sudo: required
dist: xenial
language: python
cache: pip
python:
#  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest --cov=./

after_success:
  - codecov
