# Title of the document
title: "Pandas Profiling Report"

# Number of workers (0=multiprocessing.cpu_count())
pool_size: 0

# Minify the html
minify_html: True

# Per variable type description settings
vars:
    num:
          quantiles:
                - 0.05
                - 0.25
                - 0.5
                - 0.75
                - 0.95
          skewness_threshold: 20
    cat:
        check_composition: True
low_categorical_threshold: 5

# Settings regarding warnings
cardinality_threshold: 50
check_correlation: True
correlation_overrides: []
correlation_threshold: 0.9
check_recoded: True

# which diagrams to show
missing_diagrams:
    bar: True
    matrix: True
    heatmap: True
    dendrogram: True

correlations:
    pearson: True
    spearman: True
    kendall: True
    phi_k: True

# Plot-specific settings
plot:
    # Image format (svg or png)
    image_format: "svg"
    face_color: "#337ab7"

    correlation:
        cmap: 'bwr'

    missing:
        cmap: 'RdBu'

    histogram:
        bins: 10

# The number of observations to show
n_obs_unique: 5
n_obs_bool: 3
n_extreme_obs: 5
n_freq_table_max: 10

samples:
    head: 10
    tail: 10

# When in a Jupyter notebook
notebook:
    iframe:
        height: '800px'
        width: '100%'