name: CI Lint

# Automatically lint code on release branches
on:
  push:
    branches:
      - v**

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repo

    - name: Configurating Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - uses: actions/cache@v1
      name: Cache pip dependencies
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install pip dependencies
      run: |
         pip install --upgrade pip
         pip install -r requirements.txt
         pip install -r requirements-dev.txt
         pip install -r requirements-test.txt

    - name: Code formatting
      run: make lint

    - name: Commit documentation changes
      run: |
        git add -u
        git commit -m "[skip ci] Code formatting" -a || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger build of documentation and examples
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: trigger-action
        repository: pandas-profiling/pandas-profiling
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'